/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--color-background) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        white: "rgb(var(--color-white) / <alpha-value>)",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004c6a",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#004d6b",
        "on-tertiary-fixed-variant": "#564500",
        "on-secondary-fixed": "#001e2d",
        "tertiary-fixed": "#ffe080",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-tertiary-container": "#4e3e00",
        "surface-container": "#eceef0",
        "on-primary-container": "#dde3ff",
        "on-background": "rgb(var(--color-on-surface) / <alpha-value>)",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#003fa4",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed": "#231b00",
        "inverse-primary": "#b3c5ff",
        "outline-variant": "#c3c6d6",
        "outline": "#737686",
        "on-secondary": "#ffffff",
        "tertiary-container": "#cda80c",
        "surface-dim": "#d8dadc",
        "on-error-container": "#93000a",
        "primary-container": "#1d5dda",
        "surface-container-high": "#e6e8ea",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001849",
        "on-surface-variant": "#434654",
        "surface-bright": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed-dim": "#b3c5ff",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        "secondary-fixed": "#c5e7ff",
        "surface-tint": "#0b55d2",
        "secondary-container": "#46c1fe",
        "tertiary-fixed-dim": "#eac331",
        "primary-fixed": "#dae1ff",
        "secondary-fixed-dim": "#80d0ff",
        "tertiary": "#725c00"
      },
      spacing: {
        "unit-xs": "4px",
        "unit-lg": "32px",
        "margin-mobile": "16px",
        "unit-md": "16px",
        "container-max": "1280px",
        "unit-sm": "8px",
        "section-padding": "120px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg": ["40px", {"lineHeight": "48px", "fontWeight": "700"}],
        "label-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      },
      animation: {
        "shimmer": "shimmer 2s linear infinite",
        "float": "float 6s ease-in-out infinite",
      },
      keyframes: {
        shimmer: {
          from: { backgroundPosition: "0 0" },
          to: { backgroundPosition: "-200% 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        }
      },
    },
  },
  plugins: [],
}

